// A small collection to try the program with: books and journal articles,
// each with a few details and free-form notes, in the shape of the Research
// notes layout (with PubInfo added).
export const SAMPLE = {
  name: 'Research Notes',
  fields: ['Author', 'Title', 'Year', 'PubInfo', 'Keywords', 'Notes'],
  records: [
    {
      Author: 'Thompson, E. P.',
      Title: 'The Making of the English Working Class',
      Year: '1963',
      PubInfo: 'London: Victor Gollancz',
      Keywords: 'class; labor; England; culture',
      Notes: 'Class as a relationship and an experience, not a thing: the working class was "present at its own making."\n\nStart with the preface. Compare the chapters on Methodism with the moral economy article.',
    },
    {
      Author: 'Thompson, E. P.',
      Title: 'The Moral Economy of the English Crowd in the Eighteenth Century',
      Year: '1971',
      PubInfo: 'Past & Present, no. 50: 76–136',
      Keywords: 'crowds; food riots; England; moral economy',
      Notes: 'Food riots as disciplined action, grounded in shared ideas of fair prices and customary rights.\nThe phrase "moral economy" has travelled far beyond this article; check how later writers use it.',
    },
    {
      Author: 'Ulrich, Laurel Thatcher',
      Title: 'A Midwife\'s Tale: The Life of Martha Ballard, Based on Her Diary, 1785–1812',
      Year: '1990',
      PubInfo: 'New York: Knopf',
      Keywords: 'women; medicine; diaries; Maine',
      Notes: 'Shows how much a terse daily diary can yield when read alongside town and court records.\n\nUse for the chapter on household economies.',
    },
    {
      Author: 'Scott, Joan W.',
      Title: 'Gender: A Useful Category of Historical Analysis',
      Year: '1986',
      PubInfo: 'American Historical Review, vol. 91, no. 5: 1053–75',
      Keywords: 'gender; theory; women',
      Notes: 'Gender as a primary way of signifying relationships of power.\nFor the methods chapter.',
    },
    {
      Author: 'Cronon, William',
      Title: 'Changes in the Land: Indians, Colonists, and the Ecology of New England',
      Year: '1983',
      PubInfo: 'New York: Hill and Wang',
      Keywords: 'environment; colonial; New England; property',
      Notes: 'How different ideas of property, Native and English, changed the land itself.',
    },
    {
      Author: 'Geertz, Clifford',
      Title: 'Deep Play: Notes on the Balinese Cockfight',
      Year: '1972',
      PubInfo: 'Daedalus, vol. 101, no. 1: 1–37',
      Keywords: 'anthropology; ritual; interpretation',
      Notes: 'Culture read as a text. Historians took up the approach in the 1970s and 80s; see Darnton.',
    },
    {
      Author: 'Darnton, Robert',
      Title: 'What Is the History of Books?',
      Year: '1982',
      PubInfo: 'Daedalus, vol. 111, no. 3: 65–83',
      Keywords: 'books; printing; reading; culture',
      Notes: 'Proposes a "communications circuit" running from author to publisher, printer, bookseller and reader.\nThe diagram of the circuit is worth reproducing.',
    },
    {
      Author: 'Ginzburg, Carlo',
      Title: 'The Cheese and the Worms: The Cosmos of a Sixteenth-Century Miller',
      Year: '1980',
      PubInfo: 'Baltimore: Johns Hopkins University Press',
      Keywords: 'microhistory; Italy; heresy; Inquisition',
      Notes: 'Menocchio, a miller of Friuli, through the records of his Inquisition trials.\nTranslated from the Italian (1976).',
    },
  ],
};
